services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    container_name: wolf
    restart: unless-stopped
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - XDG_RUNTIME_DIR=/tmp/sockets
    volumes:
      - /etc/wolf:/etc/wolf
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/:/dev/:rw
      - /run/udev:/run/udev:rw
      - /var/lib/wolf:/tmp/sockets
    devices:
      - /dev/dri
      - /dev/uinput
    device_cgroup_rules:
      - 'c 13:* rmw'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "47984:47984/tcp"   # HTTPS
      - "47989:47989/tcp"   # HTTP
      - "47999:47999/udp"   # Control
      - "48010:48010/tcp"   # RTSP
      - "48100:48100/udp"   # Video
      - "48200:48200/udp"   # Audio

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1280
